import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import multer from 'multer';
import {v4 as uuid} from 'uuid';
import fs from 'fs';
import path from 'path';

dotenv.config();
const app=express();
const PORT=process.env.PORT||5000;
const SECRET=process.env.JWT_SECRET||'dev-only-change-me';
app.use(cors());app.use(express.json({limit:'3mb'}));
const uploadDir=path.resolve('uploads');fs.mkdirSync(uploadDir,{recursive:true});app.use('/uploads',express.static(uploadDir));const upload=multer({dest:uploadDir});
const DB=path.resolve('data.json');const db=fs.existsSync(DB)?JSON.parse(fs.readFileSync(DB,'utf8')):{users:[],complaints:[],emergencies:[],routes:[],mode:'normal'};function save(){fs.writeFileSync(DB,JSON.stringify(db,null,2))}
function makeToken(u){return jwt.sign({id:u.id,role:u.role},SECRET,{expiresIn:'7d'})}function auth(req,res,next){try{const h=req.headers.authorization||'';req.user=jwt.verify(h.replace('Bearer ',''),SECRET);next()}catch{res.status(401).json({error:'Authentication required'})}}function current(req){return db.users.find(x=>x.id===req.user.id)}
function departmentFor(text){const t=String(text||'').toLowerCase(),out=[];if(/drain|water|flood|stagn|sewage|leak|pipe/.test(t))out.push('Water / Drainage');if(/wire|electric|pole|power|current|cable|transformer/.test(t))out.push('Electricity');if(/road|pothole|traffic|bridge|street|tree|debris|blocked/.test(t))out.push('Roads / Transport');if(/building|wall|structure|collapse|roof/.test(t))out.push('Civic / Structural Safety');if(/fire|smoke|flame/.test(t))out.push('Fire & Rescue');if(!out.length)out.push('General Civic Services');return [...new Set(out)]}
function analyse(text){const t=String(text||'').toLowerCase(),hazards=[];if(/water|flood|stagn|sewage|drain|leak|pipe/.test(t))hazards.push({problem:'Water / drainage hazard',department:'Water / Drainage',reason:'reported water can affect access and worker safety'});if(/building|wall|structure|collapse|roof/.test(t))hazards.push({problem:'Structural hazard',department:'Civic / Structural Safety',reason:'reported structural condition may create falling or debris risk'});if(/wire|electric|power|pole|cable|current|transformer/.test(t))hazards.push({problem:'Electrical hazard',department:'Electricity',reason:'exposed electrical infrastructure can create a serious contact hazard, especially around water'});if(/road|bridge|pothole|blocked|tree|debris|street/.test(t))hazards.push({problem:'Transport / access hazard',department:'Roads / Transport',reason:'reported obstruction may prevent safe public or emergency access'});const rank=h=>/Electrical hazard/i.test(h.problem)?1:/Structural hazard/i.test(h.problem)?2:/Transport/i.test(h.problem)?3:/Fire/i.test(h.problem)?4:/Water/i.test(h.problem)?5:6;const workOrder=[...hazards].sort((a,b)=>rank(a)-rank(b)).map((h,i)=>({order:i+1,problem:h.problem,department:h.department,reason:h.reason}));const problems=hazards.map(h=>h.problem);const impactChains=[];if(hazards.length>1)impactChains.push(`The reported conditions may interact. ${problems.join(' + ')} could create secondary safety or access risks if severe weather or another disaster affects the area.`);if(hazards.some(h=>h.problem==='Electrical hazard')&&hazards.some(h=>h.problem==='Water / drainage hazard'))impactChains.push('Potential interaction: exposed electrical infrastructure near reported water may endanger the public and workers. Secure/isolate the electrical hazard before water/drainage work in the affected area.');if(!impactChains.length)impactChains.push('Potential impact should be verified by the responsible authority; the system does not claim certainty or that a disaster will occur.');return{problems,departments:departmentFor(text),riskLevel:problems.length>=3?'high':problems.length===2?'medium':'low',impactChains,workOrder,source:'rules'} }
async function aiAnalyse(text){if(!process.env.OPENAI_API_KEY)return analyse(text);try{const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-4.1-mini',temperature:.1,response_format:{type:'json_object'},messages:[{role:'system',content:'You are ResQGrid risk-analysis software. Use only facts explicitly reported by the citizen. Extract all distinct hazards and relevant departments. Create a safe work order: prioritize immediate hazards that could endanger workers handling other hazards. If exposed electrical infrastructure is reported near water, electrical safety/isolation must precede water/drainage work. Generate potential impact chains, never certainty or a claim that a disaster will happen. Return JSON with problems, departments, riskLevel, impactChains, workOrder where workOrder entries have order, problem, department, reason.'},{role:'user',content:text}]})});const j=await r.json();const d=JSON.parse(j.choices?.[0]?.message?.content||'{}');return{...analyse(text),...d,source:'openai'}}catch{return analyse(text)}}
app.get('/api/health',(req,res)=>res.json({ok:true,mode:db.mode}));
app.post('/api/auth/register',async(req,res)=>{const{name,email,password,role='citizen',department=''}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Name, email and password required'});if(!['citizen','worker','admin'].includes(role))return res.status(400).json({error:'Invalid role'});if(role==='worker'&&!department)return res.status(400).json({error:'Department is required for workers'});if(db.users.some(x=>x.email.toLowerCase()===email.toLowerCase()))return res.status(409).json({error:'Email already registered'});const u={id:uuid(),name,email,password:await bcrypt.hash(password,10),role,department,createdAt:new Date().toISOString()};db.users.push(u);save();res.json({token:makeToken(u),user:{id:u.id,name:u.name,email:u.email,role:u.role,department:u.department}})});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body;const u=db.users.find(x=>x.email.toLowerCase()===String(email||'').toLowerCase());if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({error:'Invalid credentials'});res.json({token:makeToken(u),user:{id:u.id,name:u.name,email:u.email,role:u.role,department:u.department}})});
app.get('/api/me',auth,(req,res)=>{const u=current(req);res.json({id:u.id,name:u.name,email:u.email,role:u.role,department:u.department})});
app.post('/api/mode',auth,(req,res)=>{db.mode=['normal','disaster','recovery'].includes(req.body.mode)?req.body.mode:'normal';save();res.json({mode:db.mode})});
app.post('/api/complaints',auth,upload.single('photo'),async(req,res)=>{const{title,description,lat,lng,address,context='normal'}=req.body;if(!description||lat===undefined||lng===undefined)return res.status(400).json({error:'Description and location are required'});const analysis=await aiAnalyse(description);const c={id:uuid(),userId:req.user.id,title:title||description.slice(0,70),description,lat:Number(lat),lng:Number(lng),address:address||'',context,photo:req.file?`/uploads/${req.file.filename}`:null,analysis,status:'reported',workUpdates:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.complaints.push(c);save();res.json(c)});
app.get('/api/complaints',auth,(req,res)=>{let a=[...db.complaints];if(req.query.mine==='1')a=a.filter(x=>x.userId===req.user.id);if(req.user.role==='worker')a=a.filter(x=>(x.analysis?.departments||[]).some(d=>d.toLowerCase()===String(req.user.department||'').toLowerCase())||x.department===req.user.department);if(req.query.q){const q=req.query.q.toLowerCase();a=a.filter(x=>(x.title+' '+x.description+' '+x.address).toLowerCase().includes(q))}res.json(a.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)))});
app.get('/api/complaints/nearby',auth,(req,res)=>{const lat=Number(req.query.lat),lng=Number(req.query.lng),km=Number(req.query.km||5);if(!Number.isFinite(lat)||!Number.isFinite(lng))return res.status(400).json({error:'Valid location required'});const dist=(a,b)=>{const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};let a=db.complaints.map(c=>({...c,distanceKm:dist({lat,lng},c)})).filter(c=>c.distanceKm<=km);if(req.user.role==='worker')a=a.filter(x=>(x.analysis?.departments||[]).some(d=>d.toLowerCase()===String(req.user.department||'').toLowerCase()));res.json(a.sort((a,b)=>a.distanceKm-b.distanceKm))});
app.patch('/api/complaints/:id',auth,(req,res)=>{const c=db.complaints.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Not found'});if(req.user.role==='citizen'&&c.userId!==req.user.id)return res.status(403).json({error:'Not allowed'});Object.assign(c,{status:req.body.status||c.status,department:req.body.department||c.department,updatedAt:new Date().toISOString()});save();res.json(c)});
app.post('/api/complaints/:id/work-update',auth,upload.single('photo'),(req,res)=>{if(req.user.role!=='worker')return res.status(403).json({error:'Worker access required'});const c=db.complaints.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Not found'});const allowed=(c.analysis?.departments||[]).some(d=>d.toLowerCase()===String(req.user.department||'').toLowerCase());if(!allowed)return res.status(403).json({error:'This complaint is not assigned to your department'});const entry={id:uuid(),workerId:req.user.id,status:req.body.status||'in_progress',note:req.body.note||'',photo:req.file?`/uploads/${req.file.filename}`:null,createdAt:new Date().toISOString()};c.workUpdates=[...(c.workUpdates||[]),entry];c.status=entry.status;c.updatedAt=entry.createdAt;save();res.json(c)});
app.post('/api/emergencies',auth,upload.single('photo'),(req,res)=>{const{type,description,lat,lng,address}=req.body;if(!type||lat===undefined||lng===undefined)return res.status(400).json({error:'Emergency type and location required'});const e={id:uuid(),userId:req.user.id,type,description:description||'',lat:Number(lat),lng:Number(lng),address:address||'',photo:req.file?`/uploads/${req.file.filename}`:null,status:'requested',createdAt:new Date().toISOString()};db.emergencies.push(e);save();res.json(e)});
app.get('/api/emergencies',auth,(req,res)=>res.json([...db.emergencies].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))));
app.patch('/api/emergencies/:id',auth,(req,res)=>{const e=db.emergencies.find(x=>x.id===req.params.id);if(!e)return res.status(404).json({error:'Not found'});e.status=req.body.status||e.status;save();res.json(e)});
app.post('/api/routes/report',auth,(req,res)=>{const{lat,lng,description,department}=req.body;if(lat===undefined||lng===undefined||!description)return res.status(400).json({error:'Location and description required'});const r={id:uuid(),userId:req.user.id,lat:Number(lat),lng:Number(lng),description,department:department||departmentFor(description)[0],status:'affected',createdAt:new Date().toISOString()};db.routes.push(r);save();res.json(r)});
app.get('/api/routes',auth,(req,res)=>res.json(db.routes));
app.patch('/api/routes/:id',auth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Admin access required'});const r=db.routes.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:'Not found'});r.status=req.body.status||r.status;r.updatedAt=new Date().toISOString();save();res.json(r)});
app.get('/api/dashboard',auth,(req,res)=>res.json({mode:db.mode,complaints:db.complaints.length,open:db.complaints.filter(x=>x.status!=='verified').length,emergencies:db.emergencies.filter(x=>x.status!=='resolved').length,affectedRoutes:db.routes.filter(x=>x.status==='affected').length,users:db.users.length}));
app.listen(PORT,()=>console.log(`ResQGrid backend on http://localhost:${PORT}`));
